name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: semver & changelog
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          node ./scripts/generate-version-and-release-notes.js
      - name: dotnet tool install -g Amazon.Lambda.Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: upload-semver-artifacts
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          chmod +x ./scripts/*.sh
          VERSION=$(jq -r '.version' version.json)
          ./scripts/create-artifact.sh $VERSION
          ./scripts/upload-artifact.sh $VERSION
      - name: deploy-semver-artifacts
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          chmod +x ./scripts/*.sh
          VERSION=$(jq -r '.version' version.json)
          ./scripts/deploy.sh $VERSION "dev" "main"
      - name: run-performance-tests
        run: |
          chmod +x ./scripts/*.sh
          #                                  MAX_AVERAGE_RESPONSE_TIME  THREADS  SECONDS
          ./scripts/run-performance-tests.sh 250                        5        10
