name: continuous-integration
on:
  pull_request:
    branches: ["main"]
jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ensure-conventional-commits
        run: node ./scripts/ensure-conventional-commits.js $GITHUB_BASE_REF $GITHUB_HEAD_REF
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: marceloprado/has-changed-path@v1
        id: changed-src
        with:
          paths: ./src
      - name: run-unit-tests
        if: steps.changed-src.outputs.changed == 'true'
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/run-unit-tests.sh
  check-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: marceloprado/has-changed-path@v1
        id: changed-tf
        with:
          paths: ./terraform
      - name: terraform-validate
        if: steps.changed-tf.outputs.changed == 'true'
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/tfm-validate.sh $GITHUB_HEAD_REF "dev" $GITHUB_HEAD_REF
      - name: terraform-plan
        if: steps.changed-tf.outputs.changed == 'true'
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/tfm-plan.sh $GITHUB_HEAD_REF "dev" $GITHUB_HEAD_REF
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: marceloprado/has-changed-path@v1
        id: changed-tf-src-tests
        with:
          paths: ./terraform ./src ./tests
      - name: dotnet tool install -g Amazon.Lambda.Tools
        if: steps.changed-tf-src-tests.outputs.changed == 'true'
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: upload-branch-artifacts
        if: steps.changed-tf-src-tests.outputs.changed == 'true'
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/create-artifact.sh $GITHUB_HEAD_REF
          ./scripts/upload-artifact.sh $GITHUB_HEAD_REF
      - name: deploy-branch-and-run-e2e-tests
        if: steps.changed-tf-src-tests.outputs.changed == 'true'
        env:
          AWS_ACCOUNT_ID: ${{ secrets.ARTIFACTS_AWS_ACCOUNT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/deploy.sh $GITHUB_HEAD_REF "dev" $GITHUB_HEAD_REF
          ./scripts/run-e2e-tests.sh
